experiment_name: CIFAR10-classification-optuna
run_name: augmentation_flip_crop_30ep_seed42

data_dir: data

batch_size: 64
epochs: 30
learning_rate: 0.0011176293767909864
weight_decay: 0.00011257133535624675
num_workers: 0

seed: 2024

device: auto

mlflow_tracking_uri: http://127.0.0.1:5001

augmentation:
  enabled: true
  horizontal_flip: true
  random_crop: true
  crop_padding: 4
  random_rotation: true
  rotation_degrees: 15

early_stopping:
  enabled: true
  patience: 5

scheduler:
  enabled: true
  type: cosine
  min_learning_rate: 0.00001